apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-store
spec:
  resources:
    requests:
      storage: 200Mi
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      volType: ssd
